#!/usr/bin/env bash
# Mutace jadra SSE (kazda chyba MUSI shodit test_sse_jadro.py): spust vsechny paralelne, vypis souhrn.
cd "$(dirname "$0")"
M() { ./mutuj_sse.sh "$@" & }
M m01_odsazeni_noh stul_konfigurator.py 's = s.replace("SSE_ODSAZENI = 175.0", "SSE_ODSAZENI = 170.0")'
M m02_prirez_podelniku stul_konfigurator.py 's = s.replace("SSE_PODELNIK_PRIREZ = 10.0", "SSE_PODELNIK_PRIREZ = 12.0")'
M m03_spojnice stul_sse.py 's = s.replace("return float(hloubka) - 2.0 * S.SSE_JEKL", "return float(hloubka) - 70.0")'
M m04_y_jeklu stul_sse.py 's = s.replace("return float(vyska) - S.DESKA_TLOUSTKA - S.SSE_STOJKA", "return float(vyska) - S.DESKA_TLOUSTKA - S.SSE_STOJKA + 5.0")'
M m05_police_odstup stul_konfigurator.py 's = s.replace("SSE_POLICE_ODSTUP = 20.0", "SSE_POLICE_ODSTUP = 10.0")'
M m06_police_presah stul_konfigurator.py 's = s.replace("SSE_POLICE_PRESAH = 7.5", "SSE_POLICE_PRESAH = 8.5")'
M m07_zaslepka_znamenko stul_sse.py 's = s.replace("z_konce[0] - zasl_v", "z_konce[0] + zasl_v")'
M m08_deleni_desky stul_sse.py 's = s.replace("hrany = [0.0] + ([zm] if zm is not None else []) + [W]", "hrany = [0.0] + ([W / 2.0] if zm is not None else []) + [W]")'
M m09_stredni_odstup stul_konfigurator.py 's = s.replace("MIN_ODSTUP_STREDNI_NOHY = 150.0", "MIN_ODSTUP_STREDNI_NOHY = 100.0")'
M m10_peers_spojek stul_sse.py 's = s.replace("        for vl in (sp[\"rail\"], ipod[\"pred\"]):\n            peers[vl].add(sp[\"i\"])\n", "")'
M m11_orez_posunu stul_sse.py 's = s.replace("eff = min(max(posun, mb[\"min\"]), mb[\"max\"])", "eff = posun")'
M m12_zadni_vnitrni stul_sse.py 's = s.replace("zad_vnitrni = zx[1] - J ", "zad_vnitrni = zx[1] ")'
M m13_system_z_dilu stul_konfigurator.py 's = s.replace("    if pids & set(SSE_PARTS):\n        return SYSTEM_SSE", "    if False:\n        return SYSTEM_SSE")'
M m14_kota_mezery stul_koty.py 's = s.replace("(xf, podlaha, a_ + pul), (xf, podlaha, b_ - pul)", "(xf, podlaha, a_), (xf, podlaha, b_)")'
M m15_vlevo stul_sse.py 's = s.replace("z_lo = mb[\"z0\"] - eff", "z_lo = mb[\"z0\"] + eff")'
M m16_plech_strana stul_sse.py 's = s.replace("(\"zad\", D - J - S.SSE_PLECH_TL / 2.0)", "(\"zad\", D - J + S.SSE_PLECH_TL / 2.0)")'
M m17_prah_stredni stul_konfigurator.py 's = s.replace("PRAVIDLA_VYCHOZI_SYSTEMU = {SYSTEM_SSE: {\"sirka_stredni_noha\": 2000.0}}", "PRAVIDLA_VYCHOZI_SYSTEMU = {SYSTEM_SSE: {\"sirka_stredni_noha\": 1500.0}}")'
M m18_unos_flag stul_sse.py 's = s.replace("        if k in vstup and bool(vstup[k]):\n            raise", "        if False:\n            raise")'
M m19_police_hodnota stul_sse.py 's = s.replace("if out[\"police\"] not in (0, 1):", "if False:")'
M m20_box_y stul_sse.py 's = s.replace("y_hi = T - J + bs[\"box_y_hi_od_spodku\"]", "y_hi = T - J - 30.0 + bs[\"box_y_hi_od_spodku\"]")'
M m21_ceny_polozky stul_konfigurator.py 's = s.replace("if d[\"part_id\"] in NAVLEK_PARTS or d[\"part_id\"] in SSE_PARTS:", "if d[\"part_id\"] in NAVLEK_PARTS:")'
M m22_profil_delka stul_konfigurator.py 's = s.replace("SSE_PROFIL, SSE_PROFIL_DELKA, SSE_PATKA_TL = 35.0, 425.0, 3.0", "SSE_PROFIL, SSE_PROFIL_DELKA, SSE_PATKA_TL = 35.0, 400.0, 3.0")'
M m23_zive_k stul_sse.py 's = s.replace("{\"op\": \"posun\", \"ix\": sorted(int(i) for i in box), \"k\": 1.0}", "{\"op\": \"posun\", \"ix\": sorted(int(i) for i in box), \"k\": 0.5}")'
M m24_sirka_faktor stul_sse.py 's = s.replace("\"param\": \"sirka\", \"faktor\": 2.0", "\"param\": \"sirka\", \"faktor\": 1.0")'
M m25_osa_supliku stul_sse.py 's = s.replace("\"osa\": [0.0, 0.0, -1.0 if p[\"suplik_vlevo\"] else 1.0]", "\"osa\": [0.0, 0.0, 1.0]")'
M m26_preklad stul_ovladani_verejne.py 's = s.replace("(\"Levá noha SSE\", \"Left SSE leg\", \"Ľavá noha SSE\"), ", "")'
M m27_zive_ix stul_sse.py 's = s.replace("sorted(int(i) for i in box)", "sorted(int(i) for i in ibox)")'
M m28_police_menu stul_sse.py 's = s.replace("if not p[\"police\"]:\n            menu.append(pol(\"Přidat spodní polici\", {\"police\": 1}))", "menu.append(pol(\"Přidat spodní polici\", {\"police\": 1}))")'
M m29_vyska_bod stul_sse.py 's = s.replace("round(float(hi_[1]), 1), round(float((lo_[2] + hi_[2]) / 2), 1)],\n                     \"osa\": [0.0, 1.0, 0.0], \"param\": \"vyska\"", "round(float(lo_[1]), 1), round(float((lo_[2] + hi_[2]) / 2), 1)],\n                     \"osa\": [0.0, 1.0, 0.0], \"param\": \"vyska\"")'
wait
