#!/usr/bin/env bash
# Vsechny testy konfiguratoru stolu (bot8, 2026-10-02; sada 22 2026-10-05, kroky 23-26 navlek nohou (bot10) 2026-10-05, kroky 36-38 SSE stul (bot8, 2026-10-05), kroky 27-29 koty ve 3D nahledu, 30-31 panely do stran a 32-33 pravidla po systemech (bot8) 2026-10-05). Spusteni z korene repa:  bash scripts/2026-10-02_stul_testy/run_all.sh
# 1) generator + napojeni (bez DB), 2) skladani GLB, 3) API (cte jen prihlaseneho zamestnance; DB pres systemd-run), 4) prijemce stolu ve scene (Node),
# 5) stranka Generator stolu ve skutecnem Chromiu (Playwright, potrebuje internet kvuli three.js z jsdelivr).
set -u
set -o pipefail
cd "$(dirname "$0")/../.."
rc=0
echo "== 1/45 generator (nezavisle overeni napojeni)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_konfigurator.py | tail -3 || rc=1
echo "== 2/45 skladani GLB"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_glb.py | tail -3 || rc=1
echo "== 3/45 API (staff)";  systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_api.py | tail -3 || rc=1
echo "== 4/45 verejne API pro e-shop/mini-shop (kontrakt)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_shop.py | tail -3 || rc=1
echo "== 5/45 prijemce stolu ve scene (staff)"; node scripts/2026-10-02_stul_testy/test_stul_panel.js | tail -3 || rc=1
echo "== 6/45 loziskove jednotky na desce"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_loz.py | tail -3 || rc=1
echo "== 7/45 police pod vyrezem"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_vyrez_police.py | tail -3 || rc=1
echo "== 8/45 vyrobni vypis (rezny plan, desky s vyrezy, montazni postup)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_vyroba.py | tail -3 || rc=1
echo "== 9/45 ovladani ve 3D (casti, nabidky, tahy, faktory)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_ovladani.py | tail -3 || rc=1
echo "== 10/45 zive tazeni (operace proti modelu ze serveru)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_zive.py | tail -3 || rc=1
echo "== 11/45 meze posunu supliku (svetla vzdalenost od vsech nohou)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_suplik_meze.py | tail -3 || rc=1
echo "== 12/45 podpery spodni police a zkraceni desky pri hloubce nad 900 mm"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_podpery.py | tail -3 || rc=1
echo "== 13/45 zive tazeni rozmeru (vyska, sirka, hloubka): KAZDY dil sedi s modelem ze serveru"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_zive_vyska.py | tail -3 || rc=1
echo "== 14/45 nastavitelny prah hloubky (pravidla stolu, routa /api/stul/pravidla, falesna DB)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_pravidla.py 2>&1 | grep -v "WARNING in stul_api" | tail -3 || rc=1
echo "== 15/45 supliky vlevo/vpravo a svisly posun drzaku PET"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_strany_pet.py | tail -3 || rc=1
echo "== 16/45 vyskova stavitelnost polic (odstup pod deskou, mezery, meze, hash)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_police_vysky.py | tail -3 || rc=1
echo "== 17/45 odebrani jen svitidla LED (profily zustanou)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_led_svetlo.py 2>&1 | grep -v "WARNING in stul_api" | tail -3 || rc=1
echo "== 18/45 umisteni drzaku PET (noha x strana profilu)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_pet_umisteni.py | tail -3 || rc=1
echo "== 19/45 stranka Generator stolu (spolecny modul voleb + ovladani ve 3D) v prohlizeci (Chromium, pres most k verejnemu API)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-02_stul_testy/test_stul_host.js 4934 | tail -4 || rc=1
echo "== 20/45 panely vsazene do profilu, vestaveny ram, vyska stojek, elektrozlab (nezavisle mereni z AABB, mrizka 216 konfiguraci, mutace)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_panely.py | tail -3 || rc=1
echo "== 21/45 formaty tabuli laminodesky, deleni desek u stredni nohy / vestaveneho ramu (nezavisle mereni z AABB, mrizka 288 konfiguraci, mutace)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_desky_tabule.py | tail -3 || rc=1
echo "== 22/45 pocet supliku v ocelovem boxu 1 / 2 / 3 (modely, poloha, snizeni poctu, mapovani dilu, mrizka vysek, mutace)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_supliky.py | tail -3 || rc=1
echo "== 23/45 navlek nohou (jekl 40x40x2, system 35): geometrie, pravidla, mrizka, GLB, mutace"; api/venv/bin/python3 scripts/2026-10-05_system35/test_navlek.py | tail -3 || rc=1
echo "== 24/45 navlek nohou ve verejnem API (schema, cena, kusovnik, token, 3D ovladani; DB jen cte)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-05_system35/test_shop_navlek.py | tail -3 || rc=1
echo "== 25/45 navlek nohou a Vlozit do Sceny (odfiltrovani dilu, prepocet indexu)"; node scripts/2026-10-05_system35/test_navlek_scena.js | tail -3 || rc=1
echo "== 26/45 navlek nohou na strance Generator stolu 03 (system 35) v prohlizeci: vychozi stav, vypnuti, delka, nizky stul, prepnuti systemu, mobil 360 px"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --setenv=PID40=9877 --setenv=PID35=9878 --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-05_system35/test_navlek_stranka.js 4934 | tail -4 || rc=1
echo "== 27/45 koty ve 3D nahledu generatoru (vyska od podlahy, rozmery desky, vnitrni vyska, mezery a vysky polic, mezery panelu od noh; mrizka konfiguraci, GLB, mutace)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_koty.py | tail -3 || rc=1
echo "== 28/45 koty ve 3D nahledu na strankach Generator stolu 01 / 02 / 03 v prohlizeci (prepinac Koty, draty vzhled, zmena rozmeru, pohledy)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --setenv=PID40=9877 --setenv=PID35=9878 --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-02_stul_testy/test_stul_koty_stranka.js 4934 | tail -3 || rc=1
echo "== 29/45 koty a prepinac Koty jsou i na verejnych strankach (mini-shop; Robert 2026-10-05 prvky napric misty): zapnute, na uzkem okne po nacteni vypnute"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_miniweb_frontend_testy/bridge.py scripts/2026-10-02_stul_testy/test_stul_koty_verejne.js 9001 | tail -3 || rc=1
echo "== 30/45 panely VODOROVNE pohyblive, maji-li mezi nohama mezeru (posun o zadanou hodnotu, meze od noh, elektrozlab jede s panelem, hash, tah a zive operace)"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_panely_z.py | tail -3 || rc=1
echo "== 31/45 panely do stran na strance Generator stolu 01 v prohlizeci (slot, kóty mezer, uchyt ve 3D, tazeni, vratit doprostred, odkaz)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-02_stul_testy/test_stul_panely_z_stranka.js 4934 | tail -3 || rc=1
echo "== 32/45 pravidla stolu PO SYSTEMECH 30 / 35 / 40 a jen pro admina (generator, hash, cena, API s falesnou DB, verejne API)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_pravidla_systemy.py | tail -3 || rc=1
echo "== 33/45 okno Pravidla stolu na strance Generator stolu (prepinac systemu, hodnoty po systemech, jen admin; atrapy API, nic se nezapisuje)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-02_stul_testy/test_stul_pravidla_stranka.js 4934 | tail -3 || rc=1
echo "== 34/45 spodni suplik boxu (s delicimi pricky) na klik: geometrie ve 3 modelech skrine, GLB (pivot p1, pohyb drawer), mrizka bez pruniku + mutace, extra rozsahy zivého tazeni"; api/venv/bin/python3 scripts/2026-10-02_stul_testy/test_stul_suplik_klik.py | tail -3 || rc=1
echo "== 35/45 spodni suplik boxu (s delicimi pricky) v prohlizeci (klik otevre, dalsi zavre, dokola; tlacitko v HUD; novy model zavreny; bez boxu bez pohybu)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --setenv=PID40=9877 --setenv=PID35=9878 --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-02_stul_testy/test_stul_suplik_klik.js 4934 | tail -4 || rc=1
echo "== 36/45 SSE stul (system 41): jadro generatoru, geometrie z AABB, mrizka, stredni noha, supliky, hash, GLB, koty, 3D ovladani, mutace viz scripts/2026-10-05_sse/mutace_jadro.sh"; api/venv/bin/python3 scripts/2026-10-05_sse/test_sse_jadro.py | tail -3 || rc=1
echo "== 37/45 SSE stul: verejne API (schema, vyber, resolve, cena nohy jako pravidlo, objednavka, vyrobni list, fuzz; DB jen cte)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-05_sse/test_sse_shop.py | tail -3 || rc=1
echo "== 38/45 SSE stul: stranka Generator stolu 04 v prohlizeci (sloty SSE, koty, zmena rozmeru / police / supliku, hash jen se sloty SSE, prepnuti systemu, mobil 360 px)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --setenv=PID41=9879 --setenv=PID40=9877 --setenv='PRAVIDLA_TEST={}' --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-05_sse/test_sse_stranka.js 4934 | tail -3 || rc=1
echo "== 39/45 pocitadlo luxu: data ze serveru (rovina, LED, vyrezy) proti skutecnym vrcholum GLB, LuxCore (node), Johnova reference 852 lx"; api/venv/bin/python3 scripts/2026-10-05_luxy/test_osvetleni.py | tail -3 || rc=1
echo "== 40/45 pocitadlo luxu v prohlizeci (generator zamestnancu + embed + mobil: tlacitko, lazy nacteni, cifry = nezavisly vypocet, stupne 33/21 W, tazeni, vypnuti LED)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --setenv=PID40=9877 --setenv=PID35=9878 --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-05_luxy/test_luxy_host.js 4934 | tail -4 || rc=1
echo "== 41/45 zaslepky na VOLNE KONCE profilu (Robert 2026-10-06; nezavisle vzorkovani dotyku, poloha a otoceni, vedlejsi ucinky, GLB, mutace viz scripts/2026-10-06_zaslepky_konce/mutace.py)"; api/venv/bin/python3 scripts/2026-10-06_zaslepky_konce/test_zaslepky_konce.py | tail -3 || rc=1
echo "== 42/45 razitka loga na profilech stolu v modelu online nabidky (nezavisle mereni z meshe, nezanoreni, expozice, pravidla razitkovace, GLB, mutace viz scripts/2026-10-06_razitka_stolu/mutace.py)"; api/venv/bin/python3 scripts/2026-10-06_razitka_stolu/test_razitka_stolu.py | tail -3 || rc=1
echo "== 43/45 DELKY PANELU 1190 / 1481 / 1671 / 1975 (modely v katalogu, kazda delka x system, hranice a snizeni delky, mrizka konfiguraci, hash, vstup, 3D menu, ZLATY OTISK 702 konfiguraci proti stavu pred zavedenim delky; mutace viz scripts/2026-10-07_perfopanel/mutace.py)"; api/venv/bin/python3 scripts/2026-10-07_perfopanel/test_panely_delky.py | tail -3 || rc=1
echo "== 44/45 delka panelu ve verejnem API (schema, volba, snizeni + oznameni, zakazane delky s duvodem, cena = cena karet, token, shrnuti; DB jen cte)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-07_perfopanel/test_panely_delky_shop.py 2>&1 | grep -v "WARNING in stul_api" | tail -3 || rc=1
echo "== 45/45 delka panelu na strance Generator stolu 01 v prohlizeci (select, nedostupne delky, vyber 1975, snizeni pri zuzeni, odkaz, mobil)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-07_perfopanel/test_panely_delky_stranka.js 4934 | tail -4 || rc=1
echo "== LED 600 (delka svitidla 1200 / 600): generator, GLB, lux data, ZLATY OTISK 465 konfiguraci proti stavu pred zavedenim volby, geometrie z vrcholu meshe, hash, led_info, 3D menu; mutace viz scripts/2026-10-07_led600_generator/mutace.py"; api/venv/bin/python3 scripts/2026-10-07_led600_generator/test_led_delka.py | tail -3 || rc=1
echo "== LED 600: zive tazeni ramene LED se svitidly 600 (nezavisle proti modelu ze serveru)"; api/venv/bin/python3 scripts/2026-10-07_led600_generator/test_led_delka_zive.py | tail -3 || rc=1
echo "== LED 600 ve verejnem API (schema, volba, cena karty x pocet, kusovnik, nabidka kratsiho svitidla, gating aktivni karty, token, shrnuti, cache, 3D menu, lux payload; DB jen cte)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-07_led600_generator/test_led_delka_shop.py 2>&1 | grep -v "WARNING in stul_api" | tail -3 || rc=1
echo "== LED 600 a pocitadlo luxu (katalog LED600, LuxCore v Node, linearita, srovnani s LED 1200; pouze po nasazeni statickeho JS: apply_js.sh)"; api/venv/bin/python3 scripts/2026-10-07_led600_generator/test_led_delka_lux.py | tail -3 || rc=1
echo "== LED 600 na strance Generator stolu v prohlizeci + pocitadlo luxu (select delky, nabidka kratsiho svitidla, stupne podle typu svitidla, mobil)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-07_led600_generator/test_led_delka_stranka.js 4934 | tail -4 || rc=1
echo "== SVITIDLA LED RUCNE (led_pocet, led_z1..4; Robert 2026-10-08): generator, GLB, lux data, hash, led_info, 3D ovladani, zive tazeni, ZLATY OTISK 873 konfiguraci; mutace viz scripts/2026-10-08_led_rucne/mutace.py"; api/venv/bin/python3 scripts/2026-10-08_led_rucne/test_led_rucne.py | tail -3 || rc=1
echo "== SVITIDLA LED RUCNE ve verejnem API (schema, pocet, polohy, orez + oznameni, token J, shrnuti, cache, 3D ovladani cs/en/sk vc. simulace orezu hodnot starymi mezemi; DB jen cte)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-08_led_rucne/test_led_rucne_shop.py 2>&1 | grep -v "WARNING in stul_api" | tail -3 || rc=1
echo "== SVITIDLA LED RUCNE na strance Generator stolu v prohlizeci (slider poctu a polohy, odkaz, uchyt ve 3D + tazeni, nabidka Pridat / Odebrat, mobil)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-08_led_rucne/test_led_rucne_stranka.js 4934 | tail -4 || rc=1
echo "== RAZITKA LOGA NA VSECH 3D MODELECH GENERATORU (WORKFLOW pravidlo 61, Robert 2026-10-08): vychozi model s razitky, struktura GLB, vedlejsi cache, cache, komprimovana cache, vaha, meze loga; regrese bit po bitu: scripts/2026-10-08_razitka_generatory/regrese.py, mutace: mutace.py"; api/venv/bin/python3 scripts/2026-10-08_razitka_generatory/test_razitka_vychozi.py | tail -3 || rc=1
echo "== RAZITKA ve verejne route (/glb/<token> z resolve i /model/<hash>, br / gzip / identity, kolize komprimovane cache, staff model.glb; 5 systemu; DB jen cte)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-08_razitka_generatory/test_razitka_shop.py | tail -3 || rc=1
echo "== SSE SE VIDITELNE NEJMENUJE „SYSTEM 41“ (Robert 2026-10-08): texty stranek, skriptu, prekladu a vyrobniho listu bez 'system 41', pomocna funkce sysNazev, vnitrni klic 41 beze zmeny (hermeticky)"; api/venv/bin/python3 scripts/2026-10-08_sse_nazev/test_sse_nazev_texty.py | tail -3 || rc=1
echo "== RAZITKA PRI ZIVEM TAZENI (Robert 2026-10-08: \"razitka na generatoru pri tazeni zustavaji na miste\"): popis razitek ve vodicich znackach + emulace pravidla z v3d-ovladani.js nad skutecnym GLB (hermeticky)"; api/venv/bin/python3 scripts/2026-10-08_razitka_tazeni/test_razitka_tazeni.py | tail -3 || rc=1
echo "== RAZITKA PRI ZIVEM TAZENI na strance Generator stolu v prohlizeci (logo i vypln jedou s dilem, Esc je vrati, po pusteni presny model)"; systemd-run --pipe --wait --quiet --property=EnvironmentFile=/opt/konfigurator/api/.env --setenv=HOME=/root --working-directory=/opt/konfigurator api/venv/bin/python3 scripts/2026-10-02_stul_testy/_most_stul.py scripts/2026-10-08_razitka_tazeni/test_razitka_tazeni_stranka.js 4934 | tail -4 || rc=1
[ $rc -eq 0 ] && echo "VSE OK" || echo "NEKTERY TEST SELHAL"
exit $rc
